### ISSUE TITLE
kapt-  type mismatch in KMM

### ISSUE THREAD

**Issue by kondratk** [infinum/kotlin-jsonapix#25]
Hi, 
when trying to add kapt dependency like in `build.gradle.kts` of the `shared` module:

```kotlin
plugins {
    kotlin("multiplatform")
    kotlin("kapt")
    kotlin("plugin.serialization")
    id("com.android.library")
}

kotlin {
  dependencies {
     kapt("com.infinum.jsonapix:processor:1.0.0-alpha02")
}
```

I get an error:
```
Type mismatch. Required: Action<KaptExtension> Found: String
```

Already tried this walkaround- to add kapt directive into root `dependencies` of `shared` `build.gradle.kts`:

```kotlin
dependencies {//Kapt dependencies must be in top level block
    "kapt"("your-dependency")
    //Must use quoted "kapt" otherwise you get some other incorrect method with the same name -> org.gradle.api.Project.`kapt`
}
```
however, this way I cannot import annotations.
I'm using KMM project (iOS/Android). Do you have any idea what am I doing wrong?

**Comment by stjepanbanek** [comment]
Annotations are a part of the `com.infinum.jsonapix:core:1.0.0-alpha02` package.
You can import them where needed by adding: 

```
implementation("com.infinum.jsonapix:core:1.0.0-alpha02")
```

As for the `"kapt"` workaround, it should work.

**Comment by stjepanbanek** [comment]
KMM will be addressed in a future release. We can confirm that it does not work correctly at this moment.
