### ISSUE TITLE
Access to id, type

### ISSUE THREAD

**Issue by oradkovsky** [infinum/kotlin-jsonapix#31]
Hi,

This is not an issue, just a question:

Is there any way to get access to the id, type?

```
{
  "data": {
    "type": "some-type",
    "id": "some-id"
  }
}
```

`toResourceObject` enables access to "type" but "id" is always 0 - but I think it's by design

**Comment by stjepanbanek** [comment]
At the moment no, but this is a planned feature for the next release. Thanks for your question!
