### ISSUE TITLE
Handling empty arrays

### ISSUE THREAD

**Issue by oradkovsky** [infinum/kotlin-jsonapix#39]
Hello! Under spec (https://jsonapi.org/format/#fetching-resources-responses-200), we have this kind of json possible:

```
{
  "links": {
    "self": "http://example.com/articles"
  },
  "data": []
}
```
I believe - unless the changes to library happened recently - the following code will fire and fail:

```
                is JsonArray -> {
                    val first = jsonElement.jsonArray[0]
                    val type = first.jsonObject[JsonApiConstants.Keys.TYPE]
                    type?.jsonPrimitive?.content!!
                }
```

Please confirm (or not)  the issue and may be you have ideas re workaround. Thanks!

**Comment by stjepanbanek** [comment]
Hey @oradkovsky!
Thanks for your feedback!
Im currently looking into this issue as we are preparing for a new release soon. 
On one hand the JSON:API specification doesn't allow for empty arrays. Null should be sent instead. 
However, we are going to make a workaround for this, as lib shouldn't crash on something so simple
