### ISSUE TITLE
Unable find class JsonApiX in instrumental test

### ISSUE THREAD

**Issue by Alireza-Milani** [infinum/kotlin-jsonapix#43]
Hi there again.

I create a android test class and use @HiltAndroidTest to injecting dependencies into this test. but when I run android test, this error is shown
<br>
Execution failed for task ':sample:hiltJavaCompileDebugAndroidTest'.
> java.lang.NoClassDefFoundError: com/infinum/jsonapix/annotations/JsonApiX

If this problem has a solution, i appreciate say me about that

**Comment by stjepanbanek** [comment]
You need to add the core dependency as a test implementation.

```
testImplementation("com.infinum.jsonapix:core:1.0.0-beta01")
```
