### ISSUE TITLE
Issue with integration with SerialName annotator

### ISSUE THREAD

**Issue by bosko-nikcevic-infinum** [infinum/kotlin-jsonapix#57]
I was forced to remove the usage of SerialName annotator from KotlinX Serialization library together with HasOne/HasMany/etc annotators from JsonApiX library, as it didn't recognise the new variable name.

@ToshevIvan If you have something to add to the description of this issue or make it clearer

<img width="1373" alt="Screenshot 2023-11-07 at 20 46 29" src="https://github.com/infinum/kotlin-jsonapix/assets/115072515/eb31c1e3-9361-49e5-ad36-bf573b1b3392">

**Comment by thisAAY** [comment]
I will look into it

**Comment by ToshevIvan** [comment]
So as far as I remember,  when we use HasOne/HasMany kind of annotators, the field is serialized by its name, so even though the @SerialName is added it doesn't have an effect., so this leads to use the response property names with snake case or whatever are defined in there.
